# Generated by Django 4.0.2 on 2022-02-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('recipent_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('delivery_time', models.DateTimeField()),
                ('delivery_address', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
