# Generated by Django 4.0.2 on 2022-02-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_alter_courier_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
