# Generated by Django 4.0.2 on 2022-02-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0004_alter_courier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='delivery_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
