# Generated by Django 4.0.2 on 2022-02-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0005_alter_courier_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
