# Generated by Django 4.0.2 on 2022-02-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_rename_sender_chat_user_remove_chat_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='is_seen',
            new_name='is_admin',
        ),
    ]
